//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_V_I_Model.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblEstudiante
    {
       
        public int EstudianteID { get; set; }
        [Required(ErrorMessage = "El Nombre es Obligatorio")]
        public string Nombres { get; set; }
        [Required(ErrorMessage = "Los Apellidos son Obligatorios")]
        public string Apellidos { get; set; }
        [Required(ErrorMessage = "La Direccion es Obligatoria")]
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        [Required(ErrorMessage = "La Cedula es Obligatoria")]
        public string Cedula { get; set; }
        public string ImageUrl { get; set; }
    }
}
