//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_V_II_Model.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Registro = new HashSet<Registro>();
        }
    
        
        public int EmpleadoID { get; set; }
        [Required(ErrorMessage = "Debe Incluir Nombre")]
        public string Nombres { get; set; }
        [Required(ErrorMessage = "Debe Incluir Apellidos")]
        public string Apellidos { get; set; }
        [Required(ErrorMessage = "Debe Incluir Fecha De Ingreso")]
        public System.DateTime Fecha_Ingreso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registro> Registro { get; set; }
    }
}
