//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_V_II_Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro
    {
        public int RegistroID { get; set; }
        public Nullable<decimal> Sueldo { get; set; }
        public int DepartamentoID { get; set; }
        public int EmpleadoID { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
